
import numpy

# Input: path of CSV file containing h[n] generated by MATLAB
# Output: numpy array of h[n] values
def parse_hn(filepath):
    hn = np.array([])

    return hn


# Input: path of .wav audio file
# Output: numpy array of audio data values (only left channel if .wav has more than 1 channel)
def input_audio(filepath):
    audio_data = np.array([])

    return audio_data


# Input:
#   xn: data sequence to filter
#   hn: impulse response sequence
# Output: filtered sequence
def filter(xn, hn):
    yn = np.array([])

    return yn


# Input: xn: data sequence to take short time fourier transform of
# Output: stft result
def stft(xn):
    s = np.array([])

    return s


# Input: array of signal powers over time
# Output: peak values in sig_power and locations as indices
def findpeaks(sig_power):
    peaks = np.array([])
    locs = np.array([])

    return (peaks, locs)

