from funcs import *
import numpy as np

hn_path = './hn.csv'
wav_path = './fetal_heart.wav'
fsample = 44100

# Import filter h[n] generated by MATLAB
hn_arr = parse_hn(hn_path)

# Import audio data
audio_data = input_audio(wav_path)

# Calculate length of audio file
total_time = np.size(audio_data) / fsample

# Bandpass filter data
filtered_data = filter_data(audio_data, hn_arr)

# Calculate short time fourier transform
s = stft(filtered_data)

# Calculate signal power vs time
sig_power = stft2sigpower(s)

# Determine number of peaks in signal power
peaks = findpeaks(sig_power)

# Calculate frequency
num_peaks = np.size(peaks)
freq = num_peaks / total_time
print("Frequency: %f" % freq)

